name: chickHackaton
services:
  mariadb:
    image: mariadb:11.5.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: qwer1234
      MARIADB_DATABASE: chick
    ports:
      - "3307:3306" # 반드시 리스트 형태로 작성
    volumes:
      - ./db/:/var/lib/mysql